[[Xorg_libXrender]]
arch = "armv7l"
git-tree-sha1 = "c72d2b4c80974b7d14397a5726aef6e81189dce4"
libc = "glibc"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "31d43b34546f2b240f445cb096232b762c15e3d40bcb56334bb18b9c8941e4fa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXrender]]
arch = "i686"
git-tree-sha1 = "d5b78d39830bc75066a11d73433094cd6e1eb334"
libc = "musl"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "fc5dfe4396c599ff69b775e086be083bb169cac9ba45e41d7762cefa72e45174"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.i686-linux-musl.tar.gz"
[[Xorg_libXrender]]
arch = "aarch64"
git-tree-sha1 = "f3b23d83806dedb0fcfde6193c7d512127c37393"
libc = "glibc"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "8b557fed7523f50e88b09ff855b414193536ce8950460fd9899a14ee59b99574"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.aarch64-linux-gnu.tar.gz"
[[Xorg_libXrender]]
arch = "armv7l"
git-tree-sha1 = "e2621c76156d96c81d70daab2641ca74b1e86e29"
libc = "musl"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "103844920c78b8d7b139b5e5e56acc33170066034c305773cd679f85f01c9fcd"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXrender]]
arch = "aarch64"
git-tree-sha1 = "a5331ecf85277b01c291fafb2143cb00f33cce48"
libc = "musl"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "105138c13a23ab3970a891f4e765011f24ada0380855c53fa4903c2215067d7a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.aarch64-linux-musl.tar.gz"
[[Xorg_libXrender]]
arch = "x86_64"
git-tree-sha1 = "5a6ffadd1b28f4ad7f41f1d280dbc45a8b11aab4"
os = "freebsd"

    [[Xorg_libXrender.download]]
    sha256 = "eadf901c733e924a76b38790f0918905efb5c03e94d9156ae11426235e538c31"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXrender]]
arch = "i686"
git-tree-sha1 = "c4870ab898643dbe03b17edbf050dfe66b276ac8"
libc = "glibc"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "699565a94e4282453cdf3d12116ac626ee8d0129c72cbe5acbcbbb01544ad204"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.i686-linux-gnu.tar.gz"
[[Xorg_libXrender]]
arch = "x86_64"
git-tree-sha1 = "d11eea4b0b5b3c65b25dcbb5cde9ea383c1a899e"
libc = "musl"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "e8928c681d071029d2c5b5d5452a73fb7adc6ff1f2149074b27a403c0cfe82b6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.x86_64-linux-musl.tar.gz"
[[Xorg_libXrender]]
arch = "x86_64"
git-tree-sha1 = "75403c5b85cc33f558a329a28194d9c28207fb77"
libc = "glibc"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "f7667b86ad59f7fcae19418725f5009fd3d0cd84ceee02b7d25add97ae19ad0b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.x86_64-linux-gnu.tar.gz"
[[Xorg_libXrender]]
arch = "powerpc64le"
git-tree-sha1 = "62dee667514a0b3086959efee06b9181e0761122"
libc = "glibc"
os = "linux"

    [[Xorg_libXrender.download]]
    sha256 = "9ead0cff9a3c31cb153cfb19568807c813d2f77051931804a1278156494b56ea"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrender_jll.jl/releases/download/Xorg_libXrender-v0.9.10+2/Xorg_libXrender.v0.9.10.powerpc64le-linux-gnu.tar.gz"
