# Autogenerated wrapper script for Xorg_libXrender_jll for armv7l-linux-musleabihf
export libXrender

using Xorg_libX11_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `libXrender`
const libXrender_splitpath = ["lib", "libXrender.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libXrender_path = ""

# libXrender-specific global declaration
# This will be filled out by __init__()
libXrender_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libXrender = "libXrender.so.1"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"Xorg_libXrender")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    # From the list of our dependencies, generate a tuple of all the PATH and LIBPATH lists,
    # then append them to our own.
    foreach(p -> append!(PATH_list, p), (Xorg_libX11_jll.PATH_list,))
    foreach(p -> append!(LIBPATH_list, p), (Xorg_libX11_jll.LIBPATH_list,))

    global libXrender_path = normpath(joinpath(artifact_dir, libXrender_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libXrender_handle = dlopen(libXrender_path)
    push!(LIBPATH_list, dirname(libXrender_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    
end  # __init__()

